import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {

  const router = useRouter();
  const[badges, setBadges] = useState([]);

  useEffect(()=>{
    if(router.isReady){
      console.log('ready!');
      const {username} = router.query;
      getBadgeStats(username);
    }
  }, [router.isReady])

  const getBadgeStats = async (username:any) => {
    const response = await fetch(`/api/badge?username=${username}`);
    const data = await response.json();
    console.log(data);
    if(data.status === 'success')
      setBadges(data.body.matchedUser.badges);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Leetcode Badge Showcase
        </h1>

        <p className={styles.description}>
          Enter your username at{' '}
          <code className={styles.code}>/?username=YOUR_LEETCODE_USERNAME</code>
        </p>
        <div className={styles.grid}>

        {badges.length > 0 ? badges.map((badge, index)=>{
          return(
            <div className={styles.card} key={index}>
              <img src={badge.medal.config.iconGif} alt="icon" width={64} height={64} title={badge.displayName}/>
              <h4 key={index}>{badge.shortName}</h4>
            </div>
          )
        }) : null}

        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://kevzpeter.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by{' '}
          <span className={styles.logo}>
            <Image src="/logo.png" alt="Vercel Logo" width={24} height={24} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
